
;;; onncera-jetbrains-darcula-theme.el --- onncera's Jetbrains darcula -*- lexical-binding: t -*-

(deftheme onncera-jetbrains-darcula "onncera's Jetbrains darcula")

(let
	(

	(class              '((class color) (min-colors 89)))
	(subtle             "#282828")  ;; whitespace dots — barely above bg (gruber-darker bg+1)
	(fg0                "#8997a6")
	(fg1                "#a9b7c6")
	(fg2                "#cccccc")
	(fg3                "#e8e8e8")
	(fg4                "#fafafa")
	(bg0                "#111111")
	(bg1                "#181818")  ;; gruber-darker bg
	(bg2                "#303030")
	(bg3                "#313335")
	(bg4                "#383c3f")
	(bg5                "#515757")
	(bg-hl              "#214283")
	(jb-r               "#ac0909")
	(jb-g               "#36a546")
	(jb-y               "#f1eb7f")
	(key2               "#c57825")
	(key3               "#d0d0ff")
	(accent             "#ffffff")
	(mode-line-bg       "#3c3f41")
	(mode-line-bg-dark  "#2c2f31")
	(line-num           "#52494e")  ;; gruber-darker bg+4
	(builtin            "#c57825")
	(keyword            "#c57825")
	(const              "#9676ac")
	(comment            "#8a4235")  ;; exquisite-corpse red
	(doc                "#5e8759")  ;; JetBrains green for docstrings
	(func               "#ffc66d")
	(str                "#ffdd33")  ;; gruber-darker yellow for strings
	(type               "#c57825")
	(var                "#9676ac")
	(warning            "#990000")
	(jb-yellow          "#ffc66d")
	(jb-bluegreen       "#318495")
	(jb-magenta         "#9676ac")
	(jb-orange          "#c57825")
	(jb-red             "#8c0909")
	(jb-blue            "#7ca8c6")
	(jb-green           "#5e8759")

	)

	(custom-theme-set-faces 'onncera-jetbrains-darcula

	`(default                                  ((,class (:background ,bg1 :foreground ,fg1))))
	`(font-lock-builtin-face                   ((,class (:foreground ,builtin))))
	`(font-lock-comment-face                   ((,class (:foreground ,comment))))
	`(font-lock-negation-char-face             ((,class (:foreground ,const))))
	`(font-lock-reference-face                 ((,class (:foreground ,const))))
	`(font-lock-constant-face                  ((,class (:foreground ,const))))
	`(font-lock-doc-face                       ((,class (:foreground ,doc :slant normal))))     ;; JetBrains green — docstrings
	`(font-lock-doc-markup-face                ((,class (:foreground ,doc :slant normal))))     ;; treesit assigns docstrings here in python-ts-mode
	`(font-lock-function-name-face             ((,class (:foreground ,func :bold nil))))
	`(font-lock-keyword-face                   ((,class (:bold nil :foreground ,keyword))))
	`(font-lock-string-face                    ((,class (:foreground ,str))))                   ;; yellow — regular strings only
	`(font-lock-type-face                      ((,class (:foreground ,type))))
	`(font-lock-variable-name-face             ((,class (:foreground ,var))))
	`(font-lock-warning-face                   ((,class (:foreground ,jb-red :background ,bg2))))
	`(region                                   ((,class (:background ,bg-hl :extend nil))))
	`(secondary-selection                      ((,class (:inherit region))))
	`(highlight                                ((,class (:foreground ,bg3 :background ,fg3))))
	`(hl-line                                  ((,class (:background ,bg3))))
	`(fringe                                   ((,class (:background ,bg1 :foreground ,fg4))))
	`(cursor                                   ((,class (:background "white"))))
	`(show-paren-match-face                    ((,class (:background ,warning))))
	`(show-paren-match                         ((t (:foreground "yellow" :background ,bg4 :bold t))))
	`(show-paren-mismatch                      ((t (:background ,warning))))
	`(isearch                                  ((t (:foreground ,accent :background ,jb-green))))
	`(isearch-fail                             ((t (:foreground ,accent :background ,jb-red))))
	`(lazy-highlight                           ((t (:foreground ,accent :background ,jb-y))))
	`(vertical-border                          ((,class (:foreground ,bg3))))
	`(minibuffer-prompt                        ((,class (:foreground ,fg2 :weight normal))))
	`(default-italic                           ((,class (:italic t))))
	`(link                                     ((,class (:foreground ,jb-blue :underline t))))
	`(error                                    ((,class (:foreground ,jb-orange))))
	`(warning                                  ((,class (:foreground ,jb-magenta))))
	`(success                                  ((,class (:foreground ,jb-bluegreen))))
	`(dired-directory                          ((t (:inherit (font-lock-keyword-face)))))
	`(line-number                              ((,class (:inherit default :foreground ,line-num :background ,bg1))))
	`(line-number-current-line                 ((,class (:inherit line-number :foreground "#ffdd33" :weight bold))))
	`(mode-line                                ((,class (:bold nil :foreground ,fg4 :background ,mode-line-bg))))
	`(mode-line-inactive                       ((,class (:bold nil :foreground ,fg1 :background ,mode-line-bg-dark))))
	`(mode-line-buffer-id                      ((,class (:bold nil :foreground ,accent :background nil))))
	`(mode-line-highlight                      ((,class (:foreground ,keyword :box nil :weight normal))))
	`(mode-line-emphasis                       ((,class (:foreground ,fg1))))
	`(company-tooltip                          ((t (:foreground ,fg2 :background ,bg4))))
	`(company-preview-common                   ((t (:foreground unspecified :background ,bg4))))
	`(company-scrollbar-bg                     ((t (:background ,bg4))))
	`(company-scrollbar-fg                     ((t (:background ,bg0))))
	`(company-tooltip-common                   ((t (:foreground "#926297" :bold t))))
	`(company-tooltip-selection                ((t (:background ,bg-hl))))
	`(company-tooltip-annotation               ((t (:foreground ,doc))))
	`(org-document-title                       ((,class (:foreground ,jb-orange :height 1.2 :bold t))))
	`(org-level-1                              ((,class (:bold nil :foreground ,jb-orange :height 1.1))))
	`(org-level-2                              ((,class (:bold nil :foreground ,jb-magenta))))
	`(org-level-3                              ((,class (:bold nil :foreground ,jb-green))))
	`(org-level-4                              ((,class (:bold nil :foreground ,jb-bluegreen))))
	`(org-code                                 ((,class (:foreground ,fg2))))
	`(org-hide                                 ((,class (:foreground ,fg4))))
	`(org-date                                 ((,class (:underline t :foreground ,jb-green))))
	`(org-footnote                             ((,class (:underline t :foreground ,fg4))))
	`(org-link                                 ((,class (:underline t :foreground ,type))))
	`(org-special-keyword                      ((,class (:foreground ,jb-green))))
	`(org-block                                ((,class (:foreground ,fg2 :background ,bg0 :extend t))))
	`(org-quote                                ((,class (:inherit org-block :slant italic))))
	`(org-verse                                ((,class (:inherit org-block :slant italic))))
	`(org-todo                                 ((,class (:box (:line-width 1 :color ,fg3) :foreground ,keyword :bold nil))))
	`(org-done                                 ((,class (:box (:line-width 1 :color ,bg3) :bold nil :foreground ,bg4))))
	`(org-warning                              ((,class (:underline t :foreground ,warning))))
	`(org-agenda-structure                     ((,class (:weight normal :foreground ,fg3 :box (:color ,fg4) :background ,bg3))))
	`(org-agenda-date                          ((,class (:foreground ,var :height 1.1))))
	`(org-agenda-date-weekend                  ((,class (:weight normal :foreground ,fg4))))
	`(org-agenda-date-today                    ((,class (:weight normal :foreground ,keyword :height 1.2))))
	`(org-agenda-done                          ((,class (:foreground ,bg4))))
	`(org-scheduled                            ((,class (:foreground ,type))))
	`(org-scheduled-today                      ((,class (:foreground ,func :weight normal :height 1.2))))
	`(org-ellipsis                             ((,class (:foreground ,builtin))))
	`(org-verbatim                             ((,class (:foreground ,fg4))))
	`(org-document-info-keyword                ((,class (:foreground ,jb-green))))
	`(org-sexp-date                            ((,class (:foreground ,fg4))))
	`(ido-only-match                           ((,class (:foreground ,keyword))))
	`(ido-subdir                               ((,class (:weight normal :foreground ,fg0))))
	`(ido-first-match                          ((,class (:foreground ,keyword :bold nil))))
	`(gnus-header-content                      ((,class (:foreground ,keyword))))
	`(gnus-header-from                         ((,class (:foreground ,var))))
	`(gnus-header-name                         ((,class (:foreground ,type))))
	`(gnus-header-subject                      ((,class (:foreground ,func :bold nil))))
	`(trailing-whitespace                      ((,class (:foreground nil :background ,warning))))
	`(rainbow-delimiters-depth-1-face          ((,class (:foreground "gold"))))
	`(rainbow-delimiters-depth-2-face          ((,class (:foreground "orchid"))))
	`(rainbow-delimiters-depth-3-face          ((,class (:foreground "LightSkyBlue"))))
	`(rainbow-delimiters-depth-4-face          ((,class (:foreground "gold"))))
	`(rainbow-delimiters-depth-5-face          ((,class (:foreground "orchid"))))
	`(rainbow-delimiters-depth-6-face          ((,class (:foreground "LightSkyBlue"))))
	`(rainbow-delimiters-depth-7-face          ((,class (:foreground "gold"))))
	`(rainbow-delimiters-depth-8-face          ((,class (:foreground "orchid"))))
	`(rainbow-delimiters-depth-9-face          ((,class (:foreground "LightSkyBlue"))))
	`(rainbow-delimiters-unmatched-face        ((,class (:foreground ,warning))))
	`(magit-item-highlight                     ((,class (:background ,bg3))))
	`(magit-hunk-heading                       ((,class (:background ,bg3))))
	`(magit-hunk-heading-highlight             ((,class (:background ,bg3))))
	`(magit-bisect-bad                         ((t (:foreground ,jb-red))))
	`(magit-bisect-good                        ((t (:foreground ,jb-green))))
	`(magit-bisect-skip                        ((t (:foreground ,jb-orange))))
	`(magit-blame-date                         ((t (:foreground ,jb-red))))
	`(magit-blame-heading                      ((t (:foreground ,jb-orange :background ,bg3 :extend t))))
	`(magit-branch                             ((,class (:foreground ,jb-blue :weight normal))))
	`(magit-branch-current                     ((t (:foreground ,jb-blue))))
	`(magit-branch-local                       ((t (:foreground ,jb-bluegreen))))
	`(magit-branch-remote                      ((t (:foreground ,jb-green))))
	`(magit-cherry-equivalent                  ((t (:foreground ,jb-magenta))))
	`(magit-cherry-unmatched                   ((t (:foreground ,jb-bluegreen))))
	`(magit-diff-context-highlight             ((,class (:background ,bg3 :foreground ,fg3))))
	`(magit-diffstat-added                     ((t (:foreground ,jb-green))))
	`(magit-diffstat-removed                   ((t (:foreground ,jb-orange))))
	`(magit-dimmed                             ((t (:foreground ,comment))))
	`(magit-filename                           ((t (:foreground ,jb-magenta))))
	`(magit-hash                               ((t (:foreground ,comment))))
	`(magit-header-line                        ((t (:inherit nil))))
	`(magit-log-author                         ((t (:foreground ,jb-orange))))
	`(magit-log-date                           ((t (:foreground ,jb-blue))))
	`(magit-log-graph                          ((t (:foreground ,comment))))
	`(magit-mode-line-process                  ((t (:foreground ,jb-orange))))
	`(magit-mode-line-process-error            ((t (:foreground ,jb-red))))
	`(magit-process-ok                         ((t (:inherit success))))
	`(magit-process-ng                         ((t (:inherit error))))
	`(magit-section-heading                    ((t (:foreground ,jb-magenta))))
	`(magit-section-heading-selection          ((t (:foreground ,jb-orange :extend t))))
	`(magit-section-highlight                  ((t (:background ,bg3 :extend t))))
	`(magit-sequence-drop                      ((t (:foreground ,jb-red))))
	`(magit-sequence-head                      ((t (:foreground ,jb-blue))))
	`(magit-sequence-part                      ((t (:foreground ,jb-orange))))
	`(magit-sequence-stop                      ((t (:foreground ,jb-green))))
	`(magit-tag                                ((t (:foreground ,jb-yellow))))
	`(term                                     ((,class (:foreground ,fg1 :background ,bg1))))
	`(term-color-black                         ((,class (:foreground ,fg1 :background ,bg3))))
	`(term-color-blue                          ((,class (:foreground ,jb-blue :background ,func))))
	`(term-color-red                           ((,class (:foreground ,jb-red :background ,bg3))))
	`(term-color-green                         ((,class (:foreground ,jb-green :background ,bg3))))
	`(term-color-yellow                        ((,class (:foreground ,jb-yellow :background ,var))))
	`(term-color-magenta                       ((,class (:foreground ,jb-orange :background ,builtin))))
	`(term-color-cyan                          ((,class (:foreground ,jb-bluegreen :background ,str))))
	`(term-color-white                         ((,class (:foreground ,fg2 :background ,fg2))))
	`(helm-header                              ((,class (:foreground ,fg2 :background ,bg1 :underline nil :box nil))))
	`(helm-source-header                       ((,class (:foreground ,keyword :background ,bg1 :underline nil :weight normal))))
	`(helm-selection                           ((,class (:background ,bg2 :underline nil))))
	`(helm-selection-line                      ((,class (:background ,bg2))))
	`(helm-visible-mark                        ((,class (:foreground ,bg1 :background ,bg3))))
	`(helm-candidate-number                    ((,class (:foreground ,bg1 :background ,fg1))))
	`(helm-separator                           ((,class (:foreground ,type :background ,bg1))))
	`(helm-ff-directory                        ((,class (:foreground ,func :background ,bg1 :weight normal))))
	`(helm-ff-file                             ((,class (:foreground ,fg1 :background ,bg1 :weight normal))))
	`(helm-ff-executable                       ((,class (:foreground ,key2 :background ,bg1 :weight normal))))
	`(helm-ff-symlink                          ((,class (:foreground ,keyword :background ,bg1 :weight normal))))
	`(tab-bar                                  ((t (:background ,bg3))))
	`(tab-bar-tab                              ((t (:foreground ,fg2 :background ,bg5 :box (:color ,bg4)))))
	`(tab-bar-tab-inactive                     ((t (:foreground ,fg1 :background ,bg2 :box (:color ,bg4)))))
	;; GIT GUTTER — foreground holds the glyph color, background is transparent so the sign is visible
	`(git-gutter:added                         ((t (:background ,bg1 :foreground ,jb-g :weight bold))))
	`(git-gutter:deleted                       ((t (:background ,bg1 :foreground ,jb-r :weight bold))))
	`(git-gutter:modified                      ((t (:background ,bg1 :foreground ,jb-y :weight bold))))
	`(diff-hl-insert                           ((t (:background ,jb-g :foreground ,jb-g))))
	`(diff-hl-delete                           ((t (:background ,jb-r :foreground ,jb-r))))
	`(diff-hl-change                           ((t (:background ,jb-y :foreground ,jb-y))))
	`(hl-todo                                  ((t (:inverse-video t))))
	`(highlight-numbers-number                 ((t (:foreground ,jb-blue))))

	;; WHITESPACE OVERRIDES
	`(whitespace-space            ((t (:background ,bg1 :foreground ,subtle))))
	`(whitespace-tab              ((t (:background ,bg1 :foreground ,subtle))))
	`(whitespace-hspace           ((t (:background ,bg1 :foreground ,subtle))))
	`(whitespace-newline          ((t (:background ,bg1 :foreground ,subtle))))
	`(whitespace-indentation      ((t (:background ,bg1 :foreground ,subtle))))
	`(whitespace-space-after-tab  ((t (:background ,bg1 :foreground ,subtle))))
	`(whitespace-space-before-tab ((t (:background ,bg1 :foreground ,subtle))))
	`(whitespace-line             ((t (:background unspecified :foreground unspecified))))
	`(whitespace-trailing         ((t (:background "#590008"   :foreground unspecified))))

	)
)

(provide-theme 'onncera-jetbrains-darcula)

;;; onncera-jetbrains-darcula-theme.el ends here

